# Generated by Django 6.0.7 on 2026-07-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('keyword', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(db_index=True, max_length=50)),
                ('device_type', models.CharField(db_index=True, max_length=50)),
                ('source_type', models.CharField(db_index=True, max_length=100)),
                ('search_volume', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('ctr', models.FloatField(default=0.0)),
                ('rank', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
